In [1]:
import pandas as pd
import numpy as np
import xlwings as xl
import datetime as dt
import boto3

c:\Users\carlp\miniconda3\Lib\site-packages\pandas\core\arrays\masked.py:60: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.5' currently installed).
  from pandas.core import (

In [ ]:
s3 = boto3.client('s3',
                    aws_access_key_id = 'AKIASCPKVVLRRR24MAEI',
                    aws_secret_access_key = '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'
                    )
s3.download_file('carldata', 'Quality_System_Document_Use_This.xlsx', 'Quality_System_Document_Use_This.xlsx')

In [49]:
file = 'Quality_System_Document_Use_This.xlsx'
wb1 = xl.Book(file)
sht = wb1.sheets[0]
temp = sht.range('A1:N1322')
temp = temp.options(pd.DataFrame, index=False).value
temp.head()

,Date Opened,Change Control,Client,Requester,Document,Revision,Reviewer,Approver,Change Type,Impact Assessment,Quality Event,Date Closed,Days Open,Count
0,2020-10-12,20001,LPI,Lee Chen,LPI-PRO-009,000,Lee Chen,Carl Patterson,CD,None,None,2020-10-13 00:00:00,1.0,1.0
1,2020-10-12,20002,LPI,Lee Chen,LPI-SOP-311,000,Lee Chen,Carl Patterson,SOP,None,None,2021-02-25 00:00:00,136.0,1.0
2,2020-10-12,20003,LPI,Lee Chen,LPI-SOP-312,000,Lee Chen,Carl Patterson,SOP,None,None,2020-11-03 00:00:00,22.0,1.0
3,2020-10-13,20004,LPI,Lee Chen,LPI-SOP-304,001,Lee Chen,Carl Patterson,SOP,None,None,2020-10-14 00:00:00,1.0,1.0
4,2020-10-15,20005,LPI,Carl Patterson,LPI-SOP-409,001,Lee Chen,Rachel Long,SOP,None,None,2020-10-15 00:00:00,0.0,1.0

In [50]:
temp = temp.loc[:, ['Date Opened', 'Change Control', 'Client', 'Requester', 'Document', 'Revision', 'Reviewer', 'Approver', 'Date Closed', 'Days Open', 'Count']]
temp.head()

,Date Opened,Change Control,Client,Requester,Document,Revision,Reviewer,Approver,Date Closed,Days Open,Count
0,2020-10-12,20001,LPI,Lee Chen,LPI-PRO-009,000,Lee Chen,Carl Patterson,2020-10-13 00:00:00,1.0,1.0
1,2020-10-12,20002,LPI,Lee Chen,LPI-SOP-311,000,Lee Chen,Carl Patterson,2021-02-25 00:00:00,136.0,1.0
2,2020-10-12,20003,LPI,Lee Chen,LPI-SOP-312,000,Lee Chen,Carl Patterson,2020-11-03 00:00:00,22.0,1.0
3,2020-10-13,20004,LPI,Lee Chen,LPI-SOP-304,001,Lee Chen,Carl Patterson,2020-10-14 00:00:00,1.0,1.0
4,2020-10-15,20005,LPI,Carl Patterson,LPI-SOP-409,001,Lee Chen,Rachel Long,2020-10-15 00:00:00,0.0,1.0

In [52]:
weeks = temp['Date Closed'].astype(str)
days = []
for week in weeks:
    days.append(week[:-9])
temp['Date Closed'] = days

temp.head()

,Date Opened,Change Control,Client,Requester,Document,Revision,Reviewer,Approver,Date Closed,Days Open,Count,Date Closed
0,2020-10-12,20001,LPI,Lee Chen,LPI-PRO-009,000,Lee Chen,Carl Patterson,2020-10-13,1.0,1.0,2020-10-13
1,2020-10-12,20002,LPI,Lee Chen,LPI-SOP-311,000,Lee Chen,Carl Patterson,2021-02-25,136.0,1.0,2021-02-25
2,2020-10-12,20003,LPI,Lee Chen,LPI-SOP-312,000,Lee Chen,Carl Patterson,2020-11-03,22.0,1.0,2020-11-03
3,2020-10-13,20004,LPI,Lee Chen,LPI-SOP-304,001,Lee Chen,Carl Patterson,2020-10-14,1.0,1.0,2020-10-14
4,2020-10-15,20005,LPI,Carl Patterson,LPI-SOP-409,001,Lee Chen,Rachel Long,2020-10-15,0.0,1.0,2020-10-15

In [53]:
temp['Date Opened'] = temp['Date Opened'].dt.strftime('%m/%d/%Y')
temp.head()

,Date Opened,Change Control,Client,Requester,Document,Revision,Reviewer,Approver,Date Closed,Days Open,Count,Date Closed
0,10/12/2020,20001,LPI,Lee Chen,LPI-PRO-009,000,Lee Chen,Carl Patterson,2020-10-13,1.0,1.0,2020-10-13
1,10/12/2020,20002,LPI,Lee Chen,LPI-SOP-311,000,Lee Chen,Carl Patterson,2021-02-25,136.0,1.0,2021-02-25
2,10/12/2020,20003,LPI,Lee Chen,LPI-SOP-312,000,Lee Chen,Carl Patterson,2020-11-03,22.0,1.0,2020-11-03
3,10/13/2020,20004,LPI,Lee Chen,LPI-SOP-304,001,Lee Chen,Carl Patterson,2020-10-14,1.0,1.0,2020-10-14
4,10/15/2020,20005,LPI,Carl Patterson,LPI-SOP-409,001,Lee Chen,Rachel Long,2020-10-15,0.0,1.0,2020-10-15

In [54]:
temp['Date Opened'] = temp['Date Opened'].astype('datetime64[ns]')
temp['Year'] = temp['Date Opened'].dt.strftime('%Y')
temp.head()

,Date Opened,Change Control,Client,Requester,Document,Revision,Reviewer,Approver,Date Closed,Days Open,Count,Date Closed,Year
0,2020-10-12,20001,LPI,Lee Chen,LPI-PRO-009,000,Lee Chen,Carl Patterson,2020-10-13,1.0,1.0,2020-10-13,2020
1,2020-10-12,20002,LPI,Lee Chen,LPI-SOP-311,000,Lee Chen,Carl Patterson,2021-02-25,136.0,1.0,2021-02-25,2020
2,2020-10-12,20003,LPI,Lee Chen,LPI-SOP-312,000,Lee Chen,Carl Patterson,2020-11-03,22.0,1.0,2020-11-03,2020
3,2020-10-13,20004,LPI,Lee Chen,LPI-SOP-304,001,Lee Chen,Carl Patterson,2020-10-14,1.0,1.0,2020-10-14,2020
4,2020-10-15,20005,LPI,Carl Patterson,LPI-SOP-409,001,Lee Chen,Rachel Long,2020-10-15,0.0,1.0,2020-10-15,2020

In [55]:
temp['Days Open'] = temp['Days Open'].astype('float64')
temp['Year'] = temp['Year'].astype('object')
temp['Change Control'] = temp['Change Control'].astype('int64')
temp.to_csv('temp.csv', index=False)

In [56]:
Change_Year = temp.loc[:,['Year', 'Count']]
Change_Year.head()

   Year  Count
0  2020    1.0
1  2020    1.0
2  2020    1.0
3  2020    1.0
4  2020    1.0

In [ ]:
Change_Year.to_csv('Change_Year.csv', index=True)

In [57]:
Total_Year = temp.groupby('Year').agg({ "Count": "sum"})
df = pd.DataFrame(Total_Year)
df.head()

      Count
Year
2020   59.0
2021  393.0
2022  331.0
2023  428.0
2024  110.0

In [ ]:
df['Average Days Open'] = df['Days Open']
df.head()

In [ ]:
df.to_csv('Avg Days Open.csv', index=True)

In [ ]:
data = pd.read_csv('Avg Days Open.csv')
data.head()

In [ ]:
data = data.loc[:,['Year', 'Average Days Open']]
data.to_csv('Avg Days Open.csv', index=True)
data.head()

In [ ]:
Total_Year = temp.groupby('Year').agg({ "Count": "sum"})
df = pd.DataFrame(Total_Year)
df.to_csv('Number per Year.csv', index=True)
df.head()

In [2]:
open_cc = pd.read_csv('temp.csv')
open_cc=pd.DataFrame(open_cc)
open_cc.head()

,Date Opened,Change Control,Client,Requester,Document,Revision,Reviewer,Approver,Date Closed,Days Open,Count,Date Closed,Year
0,10/12/2020,20001,LPI,Lee Chen,LPI-PRO-009,0.0,Lee Chen,Carl Patterson,10/13/2020,1.0,1,10/13/2020,2020
1,10/12/2020,20002,LPI,Lee Chen,LPI-SOP-311,0.0,Lee Chen,Carl Patterson,2/25/2021,136.0,1,2/25/2021,2020
2,10/12/2020,20003,LPI,Lee Chen,LPI-SOP-312,0.0,Lee Chen,Carl Patterson,11/3/2020,22.0,1,11/3/2020,2020
3,10/13/2020,20004,LPI,Lee Chen,LPI-SOP-304,1.0,Lee Chen,Carl Patterson,10/14/2020,1.0,1,10/14/2020,2020
4,10/15/2020,20005,LPI,Carl Patterson,LPI-SOP-409,1.0,Lee Chen,Rachel Long,10/15/2020,0.0,1,10/15/2020,2020

In [3]:
open_cc = open_cc.loc[:,['Requester', 'Date Opened', 'Client', 'Document', 'Revision', 'Date Closed']]
open_cc.head()

        Requester Date Opened Client     Document  Revision Date Closed
0        Lee Chen  10/12/2020    LPI  LPI-PRO-009       0.0  10/13/2020
1        Lee Chen  10/12/2020    LPI  LPI-SOP-311       0.0   2/25/2021
2        Lee Chen  10/12/2020    LPI  LPI-SOP-312       0.0   11/3/2020
3        Lee Chen  10/13/2020    LPI  LPI-SOP-304       1.0  10/14/2020
4  Carl Patterson  10/15/2020    LPI  LPI-SOP-409       1.0  10/15/2020

In [5]:
open_cc = open_cc[open_cc['Date Closed'] == 'Open']
open_cc.to_csv('Open_Docs.csv', index=False)
open_cc.head()

             Requester Date Opened Client     Document  Revision Date Closed
1313          Yue Feng    4/8/2024    CHP  CHP-PRO-007       0.0        Open
1314   Edward Tischler    4/8/2024    LPI   LPI-FM-123       1.0        Open
1315   Edward Tischler    4/8/2024    LPI  LPI-SOP-134       1.0        Open
1316  Roxanne Tepezano   4/11/2024    CHP  CHP-MET-001       1.0        Open
1317  Roxanne Tepezano   4/11/2024    CHP  CHP-PRO-008       0.0        Open

In [ ]:
temp3 = pd.read_csv('temp3.csv')
temp3 = pd.DataFrame(temp3)
open_oos = temp3.loc[:,['Date','Requester', 'Client Code:', 'LIR_Number', 'Test', 'Closed']]
open_oos = open_oos[open_oos['Closed'] == 'Open']
open_oos.to_csv('OOS_Open.csv', index=False)

In [ ]:
file4 = 'Quality_System_Document_Use_This.xlsx'
wb4 = xl.Book(file4)
sht4 = wb4.sheets[2]
temp4 = sht4.range('A1:J191')
Open_Dev = temp4.options(pd.DataFrame, index=False).value
Open_Dev.head()

In [ ]:
Open_Dev['Date Opened'] = Open_Dev['Date Opened'].astype('datetime64[ns]')
Open_Dev['Year'] = Open_Dev['Date Opened'].dt.strftime('%Y')
Open_Dev.head()

In [ ]:
Dev_Open = Open_Dev.loc[:, ['Date Opened', 'Deviation ', 'Client', 'Closed', 'Days Open', 'Count', 'Year']]
Dev_Open.head()

In [ ]:
Average_Dev['Average Days Open'] = Open_Dev.groupby('Year').agg({ "Days Open": "mean"})
Average_Dev.to_csv('Average_Devation_per_Year.csv', index=True)
Average_Dev.head()

In [ ]:
Open_Dev = Open_Dev.loc[:,['Requester:','Date Opened', 'Deviation', 'Client', 'Description', 'Closed']]
Open_Dev = Open_Dev[Open_Dev['Closed'] == 'Open']
Open_Dev.to_csv('Open_Dev.csv', index=False)

In [ ]:
#get CAPA and Complaints information
file4 = 'Quality_System_Document_Use_This.xlsx'
wb4 = xl.Book(file4)
sht4 = wb4.sheets[1]
temp4 = sht4.range('A1:F191')
Open_CAPA = temp4.options(pd.DataFrame, index=False).value
Open_CAPA.head()

In [ ]:
Open_CAPA = Open_CAPA.loc[:,['Date Opened', 'Personnel', 'CAPA', 'Description', 'Client', 'Closed']]
Open_CAPA = Open_CAPA[Open_CAPA['Closed'] == 'Open']
Open_CAPA.to_csv('Open_CAPA.csv', index=False)
Open_CAPA.head()

In [ ]:
file4 = 'Quality_System_Document_Use_This.xlsx'
wb4 = xl.Book(file4)
sht4 = wb4.sheets[5]
temp4 = sht4.range('A1:F191')
Open_comp = temp4.options(pd.DataFrame, index=False).value
Open_comp.head()

In [ ]:
Open_comp = Open_comp.loc[:,['Date Opened', 'Personnel', 'Complaint', 'Description', 'Client', 'Closed']]
Open_comp = Open_comp[Open_comp['Closed'] == 'Open']
Open_comp.to_csv('Open_comp.csv', index=False)
Open_comp.head()