In [1]:
import pandas as pd
import numpy as np
import altair as alt
import xlwings as xl
import plotly.express as px
import datetime as dt

c:\Users\carlp\miniconda3\Lib\site-packages\pandas\core\arrays\masked.py:60: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.5' currently installed).
  from pandas.core import (

In [2]:
file = 'Quality_System_Document_Use_This.xlsx'
wb1 = xl.Book(file)
sht = wb1.sheets[0]
temp = sht.range('A1:N1322')
temp = temp.options(pd.DataFrame, index=False).value
temp.head()

,Date Opened,Change Control,Client,Requester,Document,Revision,Reviewer,Approver,Change Type,Impact Assessment,Quality Event,Date Closed,Days Open,Count
0,2020-10-12,20001,LPI,Lee Chen,LPI-PRO-009,000,Lee Chen,Carl Patterson,CD,None,None,2020-10-13 00:00:00,1.0,1.0
1,2020-10-12,20002,LPI,Lee Chen,LPI-SOP-311,000,Lee Chen,Carl Patterson,SOP,None,None,2021-02-25 00:00:00,136.0,1.0
2,2020-10-12,20003,LPI,Lee Chen,LPI-SOP-312,000,Lee Chen,Carl Patterson,SOP,None,None,2020-11-03 00:00:00,22.0,1.0
3,2020-10-13,20004,LPI,Lee Chen,LPI-SOP-304,001,Lee Chen,Carl Patterson,SOP,None,None,2020-10-14 00:00:00,1.0,1.0
4,2020-10-15,20005,LPI,Carl Patterson,LPI-SOP-409,001,Lee Chen,Rachel Long,SOP,None,None,2020-10-15 00:00:00,0.0,1.0

In [3]:
temp = temp.loc[:, ['Date Opened', 'Change Control', 'Client', 'Requester', 'Document', 'Revision', 'Reviewer', 'Approver', 'Date Closed ', 'Days Open', 'Count']]
temp.head()

,Date Opened,Change Control,Client,Requester,Document,Revision,Reviewer,Approver,Date Closed,Days Open,Count
0,2020-10-12,20001,LPI,Lee Chen,LPI-PRO-009,000,Lee Chen,Carl Patterson,2020-10-13 00:00:00,1.0,1.0
1,2020-10-12,20002,LPI,Lee Chen,LPI-SOP-311,000,Lee Chen,Carl Patterson,2021-02-25 00:00:00,136.0,1.0
2,2020-10-12,20003,LPI,Lee Chen,LPI-SOP-312,000,Lee Chen,Carl Patterson,2020-11-03 00:00:00,22.0,1.0
3,2020-10-13,20004,LPI,Lee Chen,LPI-SOP-304,001,Lee Chen,Carl Patterson,2020-10-14 00:00:00,1.0,1.0
4,2020-10-15,20005,LPI,Carl Patterson,LPI-SOP-409,001,Lee Chen,Rachel Long,2020-10-15 00:00:00,0.0,1.0

In [4]:
weeks = temp['Date Closed '].astype(str)
days = []
for week in weeks:
    days.append(week[:-9])
temp['Date Closed '] = days

temp.head()

,Date Opened,Change Control,Client,Requester,Document,Revision,Reviewer,Approver,Date Closed,Days Open,Count
0,2020-10-12,20001,LPI,Lee Chen,LPI-PRO-009,000,Lee Chen,Carl Patterson,2020-10-13,1.0,1.0
1,2020-10-12,20002,LPI,Lee Chen,LPI-SOP-311,000,Lee Chen,Carl Patterson,2021-02-25,136.0,1.0
2,2020-10-12,20003,LPI,Lee Chen,LPI-SOP-312,000,Lee Chen,Carl Patterson,2020-11-03,22.0,1.0
3,2020-10-13,20004,LPI,Lee Chen,LPI-SOP-304,001,Lee Chen,Carl Patterson,2020-10-14,1.0,1.0
4,2020-10-15,20005,LPI,Carl Patterson,LPI-SOP-409,001,Lee Chen,Rachel Long,2020-10-15,0.0,1.0

In [5]:
temp['Date Opened'] = temp['Date Opened'].dt.strftime('%m/%d/%Y')
temp.head()

,Date Opened,Change Control,Client,Requester,Document,Revision,Reviewer,Approver,Date Closed,Days Open,Count
0,10/12/2020,20001,LPI,Lee Chen,LPI-PRO-009,000,Lee Chen,Carl Patterson,2020-10-13,1.0,1.0
1,10/12/2020,20002,LPI,Lee Chen,LPI-SOP-311,000,Lee Chen,Carl Patterson,2021-02-25,136.0,1.0
2,10/12/2020,20003,LPI,Lee Chen,LPI-SOP-312,000,Lee Chen,Carl Patterson,2020-11-03,22.0,1.0
3,10/13/2020,20004,LPI,Lee Chen,LPI-SOP-304,001,Lee Chen,Carl Patterson,2020-10-14,1.0,1.0
4,10/15/2020,20005,LPI,Carl Patterson,LPI-SOP-409,001,Lee Chen,Rachel Long,2020-10-15,0.0,1.0

In [6]:
temp['Date Opened'] = temp['Date Opened'].astype('datetime64[ns]')
temp['Year'] = temp['Date Opened'].dt.strftime('%Y')
temp.head()

,Date Opened,Change Control,Client,Requester,Document,Revision,Reviewer,Approver,Date Closed,Days Open,Count,Year
0,2020-10-12,20001,LPI,Lee Chen,LPI-PRO-009,000,Lee Chen,Carl Patterson,2020-10-13,1.0,1.0,2020
1,2020-10-12,20002,LPI,Lee Chen,LPI-SOP-311,000,Lee Chen,Carl Patterson,2021-02-25,136.0,1.0,2020
2,2020-10-12,20003,LPI,Lee Chen,LPI-SOP-312,000,Lee Chen,Carl Patterson,2020-11-03,22.0,1.0,2020
3,2020-10-13,20004,LPI,Lee Chen,LPI-SOP-304,001,Lee Chen,Carl Patterson,2020-10-14,1.0,1.0,2020
4,2020-10-15,20005,LPI,Carl Patterson,LPI-SOP-409,001,Lee Chen,Rachel Long,2020-10-15,0.0,1.0,2020

In [7]:
temp['Days Open'] = temp['Days Open'].astype('float64')
temp['Year'] = temp['Year'].astype('object')
temp['Change Control'] = temp['Change Control'].astype('int64')
temp.to_csv('temp.csv', index=False)

In [8]:
Change_Year = temp.loc[:,['Year', 'Count']]
Change_Year.head()

   Year  Count
0  2020    1.0
1  2020    1.0
2  2020    1.0
3  2020    1.0
4  2020    1.0

In [9]:
Change_Year.to_csv('Change_Year.csv', index=True)

In [10]:
Total_Year = temp.groupby('Year').agg({ "Days Open": "mean"})
df = pd.DataFrame(Total_Year)
df.head()

      Days Open
Year
2020   3.847458
2021   1.643766
2022   2.006042
2023   3.726636
2024   3.519608

In [11]:
df['Average Days Open'] = df['Days Open']
df.head()

      Days Open  Average Days Open
Year
2020   3.847458           3.847458
2021   1.643766           1.643766
2022   2.006042           2.006042
2023   3.726636           3.726636
2024   3.519608           3.519608

In [12]:
df.to_csv('Avg Days Open.csv', index=True)

In [13]:
data = pd.read_csv('Avg Days Open.csv')
data.head()

   Year  Days Open  Average Days Open
0  2020   3.847458           3.847458
1  2021   1.643766           1.643766
2  2022   2.006042           2.006042
3  2023   3.726636           3.726636
4  2024   3.519608           3.519608

In [14]:
data = data.loc[:,['Year', 'Average Days Open']]
data.to_csv('Avg Days Open.csv', index=True)
data.head()

   Year  Average Days Open
0  2020           3.847458
1  2021           1.643766
2  2022           2.006042
3  2023           3.726636
4  2024           3.519608

In [15]:
Total_Year = temp.groupby('Year').agg({ "Count": "sum"})
df = pd.DataFrame(Total_Year)
df.to_csv('Number per Year.csv', index=True)
df.head()

      Count
Year
2020   59.0
2021  393.0
2022  331.0
2023  428.0
2024  110.0

In [16]:
Open_CC = pd.read_csv('temp.csv')
open_cc=pd.DataFrame(Open_CC)
open_cc.head()

,Date Opened,Change Control,Client,Requester,Document,Revision,Reviewer,Approver,Date Closed,Days Open,Count,Year
0,2020-10-12,20001,LPI,Lee Chen,LPI-PRO-009,0.0,Lee Chen,Carl Patterson,2020-10-13,1.0,1.0,2020
1,2020-10-12,20002,LPI,Lee Chen,LPI-SOP-311,0.0,Lee Chen,Carl Patterson,2021-02-25,136.0,1.0,2020
2,2020-10-12,20003,LPI,Lee Chen,LPI-SOP-312,0.0,Lee Chen,Carl Patterson,2020-11-03,22.0,1.0,2020
3,2020-10-13,20004,LPI,Lee Chen,LPI-SOP-304,1.0,Lee Chen,Carl Patterson,2020-10-14,1.0,1.0,2020
4,2020-10-15,20005,LPI,Carl Patterson,LPI-SOP-409,1.0,Lee Chen,Rachel Long,2020-10-15,0.0,1.0,2020

In [17]:
open_cc = open_cc.loc[:,['Requester', 'Date Opened', 'Client', 'Document', 'Revision', 'Closed']]
open_cc.head()

KeyError: "['Closed'] not in index"

In [18]:
open_cc = open_cc[open_cc['Closed'] == 'Open']
open_cc.to_csv('Open_Docs.csv', index=True)

KeyError: 'Closed'

In [19]:
temp3 = pd.read_csv('temp3.csv')
temp3 = pd.DataFrame(temp3)
open_oos = temp3.loc[:,['Date','Requester', 'Client Code:', 'LIR_Number', 'Test', 'Closed']]
open_oos = open_oos[open_oos['Closed'] == 'Open']
open_oos.to_csv('OOS_Open.csv', index=False)

In [20]:
file4 = 'Quality_System_Document_Use_This.xlsx'
wb4 = xl.Book(file4)
sht4 = wb4.sheets[2]
temp4 = sht4.range('A1:F191')
Open_Dev = temp4.options(pd.DataFrame, index=False).value
Open_Dev.head()

,Date Opened:,Deviation #:,Client #:,Description,Closed,Requester:
0,2020-11-02,Dev-20001,DVS-3329,Ethanol released without ID testing,2020-11-25 00:00:00,Rachel Long
1,2020-12-11,Dev-20002,N/A,Analyst not qualified to run ID test,2020-12-20 00:00:00,Charles Lo
2,2020-12-22,Dev-20003,N/A,BI ampoules not read within 48°,2020-12-28 00:00:00,Carl Patterson
3,2020-11-24,Dev-20004,DAV,Appearance form not available,2020-12-04 00:00:00,Carl Patterson
4,2021-01-19,Dev-21001,N/A,Materials from autoclave were burnd,2021-01-19 00:00:00,Michael Bresnahan

In [22]:
Total_Dev_Year = Open_Dev.groupby('Date Opened:').agg({ "Count": "sum"})
Total_Dev_Year.head()

KeyError: "Column(s) ['Count'] do not exist"

In [ ]:
Open_Dev = Open_Dev.loc[:,['Requester:','Date Opened:', 'Deviation #:', 'Client #:', 'Description', 'Closed']]
Open_Dev = Open_Dev[Open_Dev['Closed'] == 'Open']
Open_Dev.to_csv('Open_Dev.csv', index=False)

In [ ]:
#get CAPA and Complaints information
file4 = 'Quality_System_Document_Use_This.xlsx'
wb4 = xl.Book(file4)
sht4 = wb4.sheets[1]
temp4 = sht4.range('A1:F191')
Open_CAPA = temp4.options(pd.DataFrame, index=False).value
Open_CAPA.head()

In [ ]:
Open_CAPA = Open_CAPA.loc[:,['Date Opened', 'Personnel', 'CAPA', 'Description', 'Client', 'Closed']]
Open_CAPA = Open_CAPA[Open_CAPA['Closed'] == 'Open']
Open_CAPA.to_csv('Open_CAPA.csv', index=False)
Open_CAPA.head()

In [ ]:
file4 = 'Quality_System_Document_Use_This.xlsx'
wb4 = xl.Book(file4)
sht4 = wb4.sheets[5]
temp4 = sht4.range('A1:F191')
Open_comp = temp4.options(pd.DataFrame, index=False).value
Open_comp.head()

In [ ]:
Open_comp = Open_comp.loc[:,['Date Opened', 'Personnel', 'Complaint', 'Description', 'Client', 'Closed']]
Open_comp = Open_comp[Open_comp['Closed'] == 'Open']
Open_comp.to_csv('Open_comp.csv', index=False)
Open_comp.head()